using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ParkIT.Data;
using ParkIT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ParkIT.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ParkingController : ControllerBase
    {
        private readonly AppDbContext _context;

        public ParkingController(AppDbContext context)
        {
            _context = context;
        }

        // GET: api/parking
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ParkingSpot>>> GetParkingSpots()
        {
            try
            {
                return await _context.ParkingSpots.ToListAsync();
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }

        // GET: api/parking/{id}
        [HttpGet("{id}")]
        public async Task<ActionResult<ParkingSpot>> GetParkingSpot(int id)
        {
            if (id <= 0)
            {
                return BadRequest("Invalid parking spot ID.");
            }

            var spot = await _context.ParkingSpots.FindAsync(id);
            if (spot == null)
            {
                return NotFound("Parking spot not found.");
            }

            return Ok(spot);
        }

        // POST: api/parking
        [HttpPost]
        public async Task<ActionResult<ParkingSpot>> PostParkingSpot([FromBody] ParkingSpot spot)
        {
            // Validate the model state
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values
                                       .SelectMany(v => v.Errors)
                                       .Select(e => e.ErrorMessage)
                                       .ToList();
                return BadRequest(new { Message = "Validation Failed", Errors = errors });
            }

            try
            {
                // Ensure the ID is generated by the database
                spot.Id = 0;

                _context.ParkingSpots.Add(spot);
                await _context.SaveChangesAsync();

                return CreatedAtAction(nameof(GetParkingSpot), new { id = spot.Id }, spot);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }

        // PUT: api/parking/{id}
        [HttpPut("{id}")]
        public async Task<IActionResult> PutParkingSpot(int id, [FromBody] ParkingSpot spot)
        {
            if (id <= 0 || id != spot.Id)
            {
                return BadRequest("Invalid ID.");
            }

            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values
                                       .SelectMany(v => v.Errors)
                                       .Select(e => e.ErrorMessage)
                                       .ToList();
                return BadRequest(new { Message = "Validation Failed", Errors = errors });
            }

            _context.Entry(spot).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.ParkingSpots.Any(e => e.Id == id))
                {
                    return NotFound("Parking spot not found.");
                }
                else
                {
                    throw;
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }

            return NoContent();
        }

        // DELETE: api/parking/{id}
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteParkingSpot(int id)
        {
            if (id <= 0)
            {
                return BadRequest("Invalid parking spot ID.");
            }

            var spot = await _context.ParkingSpots.FindAsync(id);
            if (spot == null)
            {
                return NotFound("Parking spot not found.");
            }

            try
            {
                _context.ParkingSpots.Remove(spot);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }

            return NoContent();
        }
    }
}
